library(spatialreg)
data(oldcol, package="spdep")
lw <- spdep::nb2listw(COL.nb)
COL.OLD$fEW <- factor(COL.OLD$EW)
COL.OLD$fDISCBD <- cut(COL.OLD$DISCBD, c(0, 1.5, 3, 4.5, 6))
f <- formula(CRIME ~ INC + HOVAL + fDISCBD*fEW)
expect_warning(COL.SLX <- lmSLX(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.SLX <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.SLX <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fEW))
expect_silent(COL.SLX <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
expect_warning(COL.err <- errorsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
expect_warning(COL.lag <- lagsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
expect_warning(COL.sac <- sacsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.sac <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.sac <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.sac <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
expect_warning(COL.lag <- spBreg_lag(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
expect_warning(COL.err <- spBreg_err(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))

