library(spatialreg)
data(oldcol, package="spdep")
lw <- spdep::nb2listw(COL.nb)
COL.OLD$fEW <- factor(COL.OLD$EW)
COL.OLD$fDISCBD <- ordered(cut(COL.OLD$DISCBD, c(0, 1.5, 3, 4.5, 6)))
f <- formula(CRIME ~ INC + HOVAL + fDISCBD*fEW)
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
expect_warning(COL.SLX0 <- lmSLX(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.SLX1 <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.SLX2 <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fEW))
expect_silent(COL.SLX3 <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.SLX0a <- lmSLX(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.SLX1a <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.SLX2a <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fEW))
expect_silent(COL.SLX3a <- lmSLX(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
expect_true(isTRUE(all.equal(COL.SLX0, COL.SLX0a)))
expect_true(isTRUE(all.equal(COL.SLX1, COL.SLX1a)))
expect_true(isTRUE(all.equal(COL.SLX2, COL.SLX2a)))
expect_true(isTRUE(all.equal(COL.SLX3, COL.SLX3a)))
expect_warning(COL.err0 <- errorsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err1 <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err2 <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err3 <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.err0a <- errorsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err1a <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err2a <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err3a <- errorsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
COL.err0$timings <- COL.err0a$timings <- NULL
expect_true(isTRUE(all.equal(COL.err0, COL.err0a)))
COL.err1$timings <- COL.err1a$timings <- NULL
expect_true(isTRUE(all.equal(COL.err1, COL.err1a)))
COL.err2$timings <- COL.err2a$timings <- NULL
expect_true(isTRUE(all.equal(COL.err2, COL.err2a)))
COL.err3$timings <- COL.err3a$timings <- NULL
expect_true(isTRUE(all.equal(COL.err3, COL.err3a)))
expect_warning(COL.lag0 <- lagsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag1 <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag2 <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag3 <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.lag0a <- lagsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag1a <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag2a <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag3a <- lagsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
COL.lag0$timings <- COL.lag0a$timings <- NULL
expect_true(isTRUE(all.equal(COL.lag0, COL.lag0a)))
COL.lag1$timings <- COL.lag1a$timings <- NULL
expect_true(isTRUE(all.equal(COL.lag1, COL.lag1a)))
COL.lag2$timings <- COL.lag2a$timings <- NULL
expect_true(isTRUE(all.equal(COL.lag2, COL.lag2a)))
COL.lag3$timings <- COL.lag3a$timings <- NULL
expect_true(isTRUE(all.equal(COL.lag3, COL.lag3a)))
expect_warning(COL.sac0 <- sacsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.sac1 <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.sac2 <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.sac3 <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.sac0a <- sacsarlm(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.sac1a <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.sac2a <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.sac3a <- sacsarlm(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
COL.sac0$timings <- COL.sac0a$timings <- NULL
expect_true(isTRUE(all.equal(COL.sac0, COL.sac0a)))
COL.sac1$timings <- COL.sac1a$timings <- NULL
expect_true(isTRUE(all.equal(COL.sac1, COL.sac1a)))
COL.sac2$timings <- COL.sac2a$timings <- NULL
expect_true(isTRUE(all.equal(COL.sac2, COL.sac2a)))
COL.sac3$timings <- COL.sac3a$timings <- NULL
expect_true(isTRUE(all.equal(COL.sac3, COL.sac3a)))
expect_warning(COL.lag0 <- spBreg_lag(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag1 <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag2 <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag3 <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.lag0a <- spBreg_lag(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.lag1a <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.lag2a <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.lag3a <- spBreg_lag(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
expect_true(isTRUE(all.equal(attr(COL.lag0, "dvars"), attr(COL.lag0a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.lag1, "dvars"), attr(COL.lag1a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.lag2, "dvars"), attr(COL.lag2a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.lag3, "dvars"), attr(COL.lag3a, "dvars"))))
expect_warning(COL.err0 <- spBreg_err(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err1 <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err2 <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err3 <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.err0a <- spBreg_err(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.err1a <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.err2a <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.err3a <- spBreg_err(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
expect_true(isTRUE(all.equal(attr(COL.err0, "dvars"), attr(COL.err0a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.err1, "dvars"), attr(COL.err1a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.err2, "dvars"), attr(COL.err2a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.err3, "dvars"), attr(COL.err3a, "dvars"))))
expect_warning(COL.sac0 <- spBreg_sac(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.sac1 <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.sac2 <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.sac3 <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="0")
expect_warning(COL.sac0a <- spBreg_sac(f, data=COL.OLD, lw, Durbin=TRUE))
expect_warning(COL.sac1a <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD*fEW))
expect_warning(COL.sac2a <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL + fDISCBD))
expect_silent(COL.sac3a <- spBreg_sac(f, data=COL.OLD, lw, Durbin=~ INC + HOVAL))
Sys.setenv("SPATIALREG_CREATE_DURBIN"="")
expect_true(isTRUE(all.equal(attr(COL.sac0, "dvars"), attr(COL.sac0a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.sac1, "dvars"), attr(COL.sac1a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.sac2, "dvars"), attr(COL.sac2a, "dvars"))))
expect_true(isTRUE(all.equal(attr(COL.sac3, "dvars"), attr(COL.sac3a, "dvars"))))

